'''Value Error
Outline:
Write a program to understand how the value
 error exception works?

try:
    num = int(input("Enter your number : "))
    print(num)
except ValueError as ex :
    print("Exception ",ex)

print("I am outside the try block")'''

'''Multiple exceptions
Outline:
Write a program to check
how the exceptions and finally statement works

try:
    num1=int(input("Enter a number:  "))
    num2=int(input("Enter a number: "))
    result = num1/num2
    print("Result is :", result)
    print("Result is :", result1)

except ZeroDivisionError:
    print("Division by zero is not allowed")
except ValueError:
    print("Plese enter the numerical value")
except NameError as ex:
    print("The exception is ",ex)

except:
    print("Some error occurred")
finally: 
    print("I will execute no matter what happens")'''



'''Bye Bye
Outline:
Write a program using nested while loop. If the 
value is divided by two, 
then it will run an infinite loop of the bye.'''

valid= False

while not valid:
    try:
        n=int(input("Enter a number:"))

        while n%2==0:
            print("bye")
            valid =True

    except ValueError:
        print("Invalid")





